### ISSUE TITLE
Make __construct public to allow for dependency injection (OpenSubtitlesClient.php)

### ISSUE THREAD

**Issue by tacman** [kickasssubtitles/open-subtitles#1]
I'd like to wrap this library in a Symfony bundle to make it easier to configure the credentials and inject the client as a service.

I'm running into an issue because the constructor is marked as 'protected'.  What's the reasoning behind that, and can it be made public?

Thanks.

**Comment by grzesw** [comment]
hi there :) this is factory method design pattern - so the instance can be created only via designated method and no other way. please refer to this doc on how to use this pattern with Symfony container: https://symfony.com/doc/current/service_container/factories.html

**Comment by tacman** [comment]
Makes sense, thanks!
